### ISSUE TITLE
Implementar autenticació amb tokens a l'API

### ISSUE THREAD

**Issue by Ferran00** [Ferran00/hackernews8#26]

**Comment by victorripolles** [comment]
Autentificació: OpenAPI suporta varis tipus d'autentificació/autorització, essent el més senzill el basat en api-keys. Per tant, feu que tot usuari que es pugui loguejar a la vostra aplicació web disposi d'una api-key pròpia. Aquesta api-key s'ha de poder visualitzar a la pàgina del perfil de l'usuari loguejat de la vostra aplicació web per poder-la copiar. L'api-key s'inclourà a totes les peticions de l'API i es comprovarà que 1) sigui correcta i 2) correspongui a l'usuari apropiat en aquelles peticions que comportin canvis en el domini (POST, PUT i DELETE).
La implementació de l'API ha d'estar també desplegada a heroku, o similar.
